### ISSUE TITLE
Runner does not automatically start up again when vm reboots on v2

### ISSUE THREAD

**Issue by rubenvde** [traderepublic/Cilicon#26]
I got the vm up and running now. When the runner task is done it shutdown and starts up again as expected but then it will not start the github action runner script again so it's stuck booted up but not available to run anything.

<img width="1005" alt="Screenshot 2023-06-19 at 22 45 54" src="https://github.com/traderepublic/Cilicon/assets/2741870/ce490a1c-6bd5-4865-8640-be2201c22803">

Am I missing a setting that resolves this?

**Comment by Marcocanc** [comment]
@rubenvde Thanks for reporting this. Would you mind sharing your configuration (you may redact any irrelevant/secret information) and providing more information on the image you're using? I haven't come across this behaviour yet but will do my best to find a fix.

**Comment by rubenvde** [comment]
@Marcocanc thanks for helping out.
So I tried connecting to the SSH from the host computer in the terminal after reboot, that works.

This is my cilicon.yml file.
```
source: ~/VM2.bundle
provisioner:
  type: github
  config:
    appId: 000000
    organization: XXXXX
    privateKeyPath: ~/CI/github.pem
hardware:
  ramGigabytes: 16
  connectsToAudioDevice: false
directoryMounts:
  - hostPath: ~/CI/VM Cache 2
    guestFolder: Cache
    readOnly: false
autoTransferImageVolume: /Volumes/Cilicon Drive
runnerName: the-Swift-Samurai-2
editorMode: false
```
How I get to the image is from v1 I downloaded the latest ipsw version. And via editorMode I installed Xcode and updated the system ones.

Let me know if you need more information.
