### ISSUE TITLE
"home" could not be copied

### ISSUE THREAD

**Issue by torarnv** [traderepublic/Cilicon#28]
<img width="727" alt="image" src="https://github.com/traderepublic/Cilicon/assets/7536/127c95ce-d82f-458a-b5d4-a53b72edd0cb">

After running for the first time.

**Comment by torarnv** [comment]
Also, this, which looks worrying:

<img width="727" alt="image" src="https://github.com/traderepublic/Cilicon/assets/7536/99dba587-4f54-4cde-8d52-9e6e936a119d">

**Comment by torarnv** [comment]
The default config has `vmClonePath: /Users/torarne/vmclone`, but it looks like the code expects it to be `/` terminated, otherwise it tries to create  `/Users/torarne/vmclonehome`, `/Users/torarne/vmcloneusr`, etc

**Comment by torarnv** [comment]
This is scary:

<img width="727" alt="image" src="https://github.com/traderepublic/Cilicon/assets/7536/6cf256f2-bda7-4498-94a4-e0193d84eb1f">

**Comment by Marcocanc** [comment]
Would you mind sharing your full `cilicon.yml` file so I can try to look into it (feel free to redact any confidential info)?

**Comment by torarnv** [comment]
I installed the app, ran it for the first time, got this:

<img width="727" alt="image" src="https://github.com/traderepublic/Cilicon/assets/7536/598ac47f-ac96-4603-a9eb-8bc3c4d2e989">

Entered a local tart VM name (`ventura-vanilla:13.4`) based on 
```
❯ tart list
Source Name                         Size Running
local  monterey-vanilla:12.6        18   false
local  sonoma-vanilla:14.0-23A5257q 31   false
local  sonoma-vanilla:14.0-beta     18   false
local  ventura-vanilla:13.4         16   false
```
Which generated:
``` 
❯ cat ~/cilicon.yml
provisioner:
  type: script
  config:
    run: echo Hello World && sleep 10 && echo Shutting down
hardware:
  ramGigabytes: 8
  display:
    width: 1920
    height: 1200
    pixelsPerInch: 80
  connectsToAudioDevice: false
directoryMounts: []
source: ''
vmClonePath: /Users/torarne/vmclone
editorMode: false
retryDelay: 3
sshCredentials:
  username: admin
  password: admin
```
Which put this in my home dir:

```
drwxr-xr-x@   2 torarne  staff     64 Jun 27 16:19 vmclone
lrwxr-xr-x@   1 torarne  staff     25 Jun 27 12:08 vmclonehome -> /System/Volumes/Data/home
drwxr-xr-x@   3 torarne  staff     96 Jun 27 16:19 vmcloneusr
```
