### ISSUE TITLE
Issue with Swift-nio-channel on mac mini Sequoia 15.5

### ISSUE THREAD

**Issue by fberndtsson** [traderepublic/Cilicon#66]
From readme file:

`There seems to be an issue with swift-nio based SSH on macOS 15.0-15.3.X. Please use macOS 15.4+ for a more reliable experience.`

**System I have:**
Hardware: mac mini m3
OS: Sequoia 15.5
xcode: 16.4

**cilicon.yml** 
```
source: oci://ghcr.io/cirruslabs/macos-sequoia-xcode:16
provisioner:
  type: gitlab
  config:
    gitlabURL: https://gitlab.com
    runnerToken: token-that-is-secret
    downloadLatest: false
```

Running with: https://github.com/traderepublic/Cilicon/releases/tag/v2.2.3
```
---------- Starting Up ----------
---------- Starting Up ----------
---------- Starting Up ----------
zsh: no such file or directory: ./gitlab-runner
The operation couldn’t be completed. (Citadel.SSHClient.CommandFailed error 1.)
---------- Shutting Down ----------
---------- Starting Up ----------
```

Most often it fails for some "swift-nio-channel" error without any additionally information, which i suppose is related to the issue from Readme. Do we have any idea/workaround of how to fix/troubleshoot it further?

**_Additional_**
The issue started after changing the image from: source: oci://ghcr.io/cirruslabs/macos-sonoma-xcode:16 --> to the new sequoia.
I have successfully started and logged into the image with tart with the command: `tart run sequoia-xcode-16-3`
I tried various other images with same nio-channel issue
* oci://ghcr.io/cirruslabs/macos-sonoma-xcode:16.1
* sequoia-xcode-16-3
* sequoia-xcode-16-2
* sequoia-xcode-16-1
* sequoia-xcode-16
